name: Basic Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - main


jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    
    steps:
      - name: No params
        uses: Berke-Ates/LoC
